# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frags < Formula
  desc "FRAGS CLI"
  homepage "https://github.com/fragshq/frags"
  version "v1.0.0-rc9"
  license "AGPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc9/frags_v1.0.0-rc9_darwin_amd64.tar.gz"
      sha256 "35234a14dfb03e2533e9676b3a33a3b1ee1db1a3a474da5481ea80b6a0e067c2"

      define_method(:install) do
        bin.install "frags"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc9/frags_v1.0.0-rc9_darwin_arm64.tar.gz"
      sha256 "45e333568e43a946178c97ead91baa694feb6b2e226a9729d05e3540f82e4f37"

      define_method(:install) do
        bin.install "frags"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc9/frags_v1.0.0-rc9_linux_amd64.tar.gz"
      sha256 "2a8c4071c227098ed79aaffd989907ba4c28a4badd76cbb9f0758c81685da69e"
      define_method(:install) do
        bin.install "frags"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc9/frags_v1.0.0-rc9_linux_arm64.tar.gz"
      sha256 "17fbced52067b5e5e03adcf7ebdb753cdf46846afd2d92e0afb4da6cce927277"
      define_method(:install) do
        bin.install "frags"
      end
    end
  end
end
