# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frags < Formula
  desc "FRAGS CLI"
  homepage "https://github.com/fragshq/frags"
  version "v1.0.0-rc8"
  license "AGPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc8/frags_cli.v1.0.0-rc8_darwin_amd64.tar.gz"
      sha256 "e3896c9493118630b6c2cbc63a7bc6fbfcbbb81408a7443e7e0d98cf1c9b0f84"

      define_method(:install) do
        bin.install "frags"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc8/frags_cli.v1.0.0-rc8_darwin_arm64.tar.gz"
      sha256 "d7d8bc38cfc196006f333c8f248346b7e72d14c05337ecd913a1f6f88fbfb4d2"

      define_method(:install) do
        bin.install "frags"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc8/frags_cli.v1.0.0-rc8_linux_amd64.tar.gz"
      sha256 "0d81d11c89c176c9bcd0ebf26c34d3732c2a18e450c738b71b5371349b49c195"
      define_method(:install) do
        bin.install "frags"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fragshq/frags/releases/download/cli%2Fv1.0.0-rc8/frags_cli.v1.0.0-rc8_linux_arm64.tar.gz"
      sha256 "162f4ece83eb1b603a705c51d0a05914b3eb9cbc7d14602819cd9f2ae0e34aaa"
      define_method(:install) do
        bin.install "frags"
      end
    end
  end
end
